updated to HPA version 20.0
lgatto/hpar pull request #7
Opened 2020-11-24 11:04 UTC by ManonMartin

2020-11-24 16:18 UTC, lgatto requested changes

2020-11-24 16:18 UTC, lgatto commented on DESCRIPTION
> +Version: 1.33.3
This should still be version 1.33.2 (see below)

2020-11-24 16:18 UTC, lgatto commented on NEWS.md
> +- Update to HPA release 20.0 <2020-11-24 Thu>
Add this to version 1.33.2 and remove 'Nothing yet'.

Whenever I push to Bioconductor (in this case, version 1.33.1), I bump the version on github (to show that it is potentially different), and simply say 'Nothing yet' in the NEWS file.

2020-11-26 11:15 UTC, ManonMartin reviewed
Sorry I missed this step, thanks for the correction

2020-11-26 15:02 UTC, lgatto approved these changes

2020-11-26 15:04 UTC, merged